### ISSUE TITLE
[feature request] get variable names & summary stats 

### ISSUE THREAD

**Issue by tim-salabim** [bjornharrtell/flatgeobuf#62]
In https://github.com/r-spatial/leafem/blob/master/inst/htmlwidgets/lib/FlatGeoBuf/fgb.js#L173-L200 I am allowing a user to specify field names of a flatgeobuf file to scale different aspects of the visual representation of a leaflet layer depending on the values of those fields. 

```js
updateStyle = function(style_obj, feature, scale, scaleValues) {
  var cols = Object.keys(style_obj);
  var vals = Object.values(style_obj);

  var out = {};

  for (i = 0; i < cols.length; i++) {
    if (vals[i] === null) {
      out[cols[i]] = feature.properties[cols[i]];
    } else {
      if (scaleValues !== undefined) {
        //if (Object.keys(feature.properties).includes(vals[i])) {
        if (scaleValues[i] === true) {
          vals[i] = rescale(
            feature.properties[vals[i]]
            , scale[cols[i]].to[0]
            , scale[cols[i]].to[1]
            , scale[cols[i]].from[0]
            , scale[cols[i]].from[1]
          );
        }
      }
      out[cols[i]] = vals[i];
    }
  }

  return out;
};
```

This can be used to map numeric variables to point size (radius), line width (weight), line opacity (opacity) and fill opacity (fillOpacity). The user will provide the field names in the `scaleFields` argument and will need to provide some scaling rules in the `scale` argument. The `scale` is an object with (up to) 4 key-value pairs for each scaleField, e.g. 

`{opacity:{to_min:0, to_max:1, from_min:<min_field_value>, from_max:<max_field_value>}}`

At the moment this poses two challenges:

1. I don't know the structure of the attribute table
2. I don't know the min/max values of the field(s) in question

For 1. I am currently inspecting the first `result` of `deserializeStream` to get the field names and compare them to the `style` object [here](https://github.com/r-spatial/leafem/blob/master/inst/htmlwidgets/lib/FlatGeoBuf/fgb.js#L48-L59). The relevant part is:

```js
if (scaleFields === undefined &
                result.value.properties !== undefined) {
              var vls = Object.values(style);
              scaleFields = [];
              vls.forEach(function(name) {
                if (name in result.value.properties) {
                  scaleFields.push(true);
                } else {
                  scaleFields.push(false);
                }
              });
            }
```
This is fine unless fields are missing from the first `result.value.properties` because of missing data. The fetch API seems to drop the fields alltogether if the value for the field is missing/undefined. Hence, being able to read field names prior to the fetch call would be great so I can be sure to capture all field names present in the file.

For 2. I am currently relying on user input for `from_min` and `from_max` as I don't see any other way of calculating the overall min and max data values for a given field when data is being streamed. So something similar to `ogrinfo` including min/max values for each field would be great (unless of course the overhead for calculating these will be too large).

Here's an example where I map radius, fillOpacity and weight to 50k points (gif is too large for github, hence the link to the tweet). 

https://twitter.com/TimSalabim3/status/1267424569398374403

Hope this is clear enough.

**Comment by bjornharrtell** [comment]
I realize it's already possible if using the generic deserializer implementation (https://unpkg.com/flatgeobuf@3.2.1/dist/doc/modules/_generic_.html#deserialize). I assume you use the geojson one? The generic deserializer would be more performant. It leaves it up to the consumer to define the callback that will transform the raw FlatGeobuf representation into what you want. It's the fromFeature parameter at https://unpkg.com/flatgeobuf@3.2.1/dist/doc/modules/_generic_.html#deserialize which has the signature documented at https://unpkg.com/flatgeobuf@3.2.1/dist/doc/modules/_generic_featurecollection_.html#fromfeaturefn. So for each feature this function will get the raw Feature and HeaderMeta. The HeaderMeta has everthing you want (I think?)

That said, I'm working on providing an optional callback to the geojson deserializer so that you can get the HeaderMeta.

**Comment by bjornharrtell** [comment]
Done :) See https://unpkg.com/flatgeobuf@3.3.1/dist/doc/modules/_geojson_.html.

**Comment by tim-salabim** [comment]
Thanks for the quick implementation!
However, I am at a loss with how to get the header info... Would you mind showing me how to get the header info from `data_fl` at this point in the code, where `data_fl` is either the href of a attachment or a url?

https://github.com/r-spatial/leafem/blob/master/inst/htmlwidgets/lib/FlatGeoBuf/fgb.js#L22

Also, I am struggling to pass a `Rect` to `deserialize` to only read parts of the `response.body` here

https://github.com/r-spatial/leafem/blob/master/inst/htmlwidgets/lib/FlatGeoBuf/fgb.js#L28

I am really sorry, but I find it quite hard to figure things out without having examples given that I have pretty much zero javascript knowldge...

**Comment by bjornharrtell** [comment]
You are writing an awful lot of JavaScript without having any knowledge! :)

It's difficult for me to provide specific guidance in that code because it's quite involved. But perhaps it will help you if I can make an example on getting and using the header data at https://bjornharrtell.github.io/flatgeobuf/examples/leaflet?

**Comment by bjornharrtell** [comment]
Might want to consider watching https://www.youtube.com/watch?v=XFTOG895C7c and older material from mr. Crockford, he has a way of convincing you of using lint and learning in general.

**Comment by tim-salabim** [comment]
I know, and I'm not proud of asking for help like this. 

It would be great if you could add an example of how to get and use the header data in your leaflet example. If you could also provide an example there of how to only access a certain area subset using rect, that would be perfect. I really appreciate all the help you provided in the past!

**Comment by bjornharrtell** [comment]
No problem, I feel you are contributing to this project so I'm glad to help.

**Comment by bjornharrtell** [comment]
I've updated the example at https://bjornharrtell.github.io/flatgeobuf/examples/leaflet so that it uses the third argument to deserialize with callback handleHeaderMeta that will get the header data and I present it in full using a JSON renderer. Hope that makes it clear how you can get the header information.

Filtering only works if you give an URL as in input (unless you go lower level) and the web server needs to support ranged requests which raw.githubusercontent.com does not so I cannot publish a working version. See https://github.com/bjornharrtell/flatgeobuf/blob/master/examples/leaflet/index_filtered.js for something that works for me locally. However I strongly recommend *not* filtering client side in a client server situation for two reasons:

* If you produce flatgeobuf on demand it should be filtered already
* JavaScript reference implementation for filtering is suboptimal due to lacking I/O cache (see https://github.com/bjornharrtell/flatgeobuf/issues/50)

Also note that spatial indexing is only important if you need client side filtering so if you do not need that it would be faster and save space to produce prefiltered flatgeobuf without spatial index.

**Comment by tim-salabim** [comment]
Thanks so much Björn!! This was exactly what I needed. 

I agree that pre-filtering is desirable, given that most of the time we do indeed create the flatgeobuf before we render it. There are scenarios where a spatial filter would be handy, but I'll see if we can solve them some other way (if the come up at a certain point).
