### ISSUE TITLE
Is GeoJSON so slow ?

### ISSUE THREAD

**Issue by kalyanmysore** [bjornharrtell/flatgeobuf#74]
While I see that flatgeobuf is better than shapefiles, I was surprised by how much faster than GeoJSON it is.
Is that because GeoJSON uses a DOM style method of loading the entire thing first ? Or is it because there is no index in the file itself, requiring a lot of file scanning ?
This isnt really an issue with flatgeobuf itself. I was just wondering if there is a better way to use GeoJSON that doesnt make it look so bad in the benchmarks.

**Comment by bjornharrtell** [comment]
Short story is yes GeoJSON is slow and will always lose.

One hack is to use newline delimited GeoJSON which allow streaming parse. It will still be slower because JSON requires you to parse the text. FlatGeobuf needs no parse step, it can be used as is by the computer.

As for use case involving spatial filter there is no workaround as far as I know. If you do not have a spatial index it will be slow to spatial filter no matter what.
